// ============================================================
// Quiz "Pour qui voter ?" — questions et positions des candidats
// Adapte du concept de candidatspresidentielles2027.fr (methode
// transparente : distance entre reponse et position, ponderee
// x1.5 sur les themes prioritaires choisis).
// ============================================================

const QUIZ_THEMES = [
  { id:'economie', label:'Économie / fiscalité' },
  { id:'immigration', label:'Immigration / asile' },
  { id:'ecologie', label:'Écologie / énergie' },
  { id:'institutions', label:'Institutions' },
  { id:'europe', label:'Europe' },
  { id:'securite', label:'Sécurité / justice' },
  { id:'social', label:'Social / travail' }
];

const QUIZ_LIKERT = [
  { value:-2, label:"Pas du tout d'accord" },
  { value:-1, label:"Plutôt pas d'accord" },
  { value:0, label:'Neutre / je ne sais pas' },
  { value:1, label:"Plutôt d'accord" },
  { value:2, label:"Tout à fait d'accord" }
];

const QUIZ_QUESTIONS = [
  { id:'q1', theme:'economie', text:'Réduire la dette et la dépense publique doit primer sur de nouvelles dépenses sociales.', positions:{philippe:2,lepen:1,attal:1,melenchon:-2,retailleau:2,bertrand:1,glucksmann:0,guedj:-1,dupontaignan:1,lisnard:1,batho:-1,philippot:0,asselineau:0,arthaud:-2,roussel:-2,tondelier:-2,cazeneuve:1,faure:-1,ruffin:-2,wauquiez:2,devillepin:1,zemmour:1,bouamrane:1,egger:0,mikolajczak:0,kazib:-2,branco:-1,brun:0,maurel:0,verdier:0,massard:0,labib:0,lalanne:0,mathieu:0,durif:0,royal:-1,jadot:-2,rousseau:-2,autain:0} },
  { id:'q2', theme:'social', text:'Les salaires les plus bas (SMIC et minima) doivent être fortement revalorisés.', positions:{philippe:0,lepen:1,attal:0,melenchon:2,retailleau:1,bertrand:1,glucksmann:1,guedj:1,dupontaignan:2,lisnard:0,batho:0,philippot:0,asselineau:2,arthaud:2,roussel:2,tondelier:2,cazeneuve:0,faure:2,ruffin:2,wauquiez:-1,devillepin:1,zemmour:1,bouamrane:2,egger:0,mikolajczak:0,kazib:2,branco:1,brun:0,maurel:0,verdier:0,massard:0,labib:0,lalanne:0,mathieu:0,durif:0,royal:1,jadot:2,rousseau:2,autain:0} },
  { id:'q3', theme:'social', text:'La réforme des retraites à 64 ans doit être abrogée ou fortement assouplie.', positions:{philippe:-1,lepen:0,attal:-2,melenchon:2,retailleau:-2,bertrand:0,glucksmann:1,guedj:2,dupontaignan:0,lisnard:-1,batho:1,philippot:1,asselineau:1,arthaud:2,roussel:2,tondelier:2,cazeneuve:-1,faure:2,ruffin:2,wauquiez:-2,devillepin:0,zemmour:-2,bouamrane:1,egger:0,mikolajczak:0,kazib:2,branco:1,brun:0,maurel:0,verdier:0,massard:0,labib:0,lalanne:0,mathieu:0,durif:0,royal:1,jadot:2,rousseau:2,autain:0} },
  { id:'q4', theme:'immigration', text:'L\'immigration doit être nettement plus restrictive (contrôles, conditions d\'accès, regroupement familial).', positions:{philippe:0,lepen:2,attal:0,melenchon:-2,retailleau:2,bertrand:2,glucksmann:-1,guedj:-1,dupontaignan:2,lisnard:1,batho:-1,philippot:2,asselineau:2,arthaud:-1,roussel:-2,tondelier:-2,cazeneuve:0,faure:-1,ruffin:0,wauquiez:2,devillepin:1,zemmour:2,bouamrane:1,egger:0,mikolajczak:0,kazib:-2,branco:-1,brun:0,maurel:0,verdier:0,massard:0,labib:0,lalanne:0,mathieu:0,durif:0,royal:-1,jadot:-2,rousseau:-2,autain:0} },
  { id:'q5', theme:'securite', text:'Renforcer la sécurité, la justice et l\'exécution des peines doit être une priorité absolue.', positions:{philippe:2,lepen:2,attal:1,melenchon:-1,retailleau:2,bertrand:2,glucksmann:0,guedj:0,dupontaignan:2,lisnard:2,batho:-1,philippot:2,asselineau:1,arthaud:-2,roussel:-1,tondelier:-1,cazeneuve:2,faure:0,ruffin:0,wauquiez:2,devillepin:2,zemmour:2,bouamrane:2,egger:0,mikolajczak:0,kazib:-2,branco:-1,brun:0,maurel:0,verdier:0,massard:0,labib:0,lalanne:0,mathieu:0,durif:0,royal:1,jadot:-1,rousseau:-1,autain:0} },
  { id:'q6', theme:'ecologie', text:'La priorité écologique doit être la sobriété et la décroissance plutôt que la croissance du PIB.', positions:{philippe:0,lepen:0,attal:0,melenchon:1,retailleau:0,bertrand:0,glucksmann:-1,guedj:1,dupontaignan:0,lisnard:0,batho:2,philippot:0,asselineau:0,arthaud:1,roussel:-1,tondelier:2,cazeneuve:-1,faure:0,ruffin:1,wauquiez:-2,devillepin:-1,zemmour:-2,bouamrane:-1,egger:0,mikolajczak:1,kazib:0,branco:0,brun:0,maurel:0,verdier:0,massard:0,labib:0,lalanne:0,mathieu:0,durif:0,royal:0,jadot:2,rousseau:2,autain:0} },
  { id:'q7', theme:'ecologie', text:'Le nucléaire doit rester au cœur de la stratégie énergétique française.', positions:{philippe:1,lepen:2,attal:1,melenchon:0,retailleau:2,bertrand:1,glucksmann:0,guedj:0,dupontaignan:2,lisnard:1,batho:-1,philippot:2,asselineau:2,arthaud:0,roussel:2,tondelier:-2,cazeneuve:2,faure:0,ruffin:0,wauquiez:2,devillepin:1,zemmour:2,bouamrane:0,egger:0,mikolajczak:2,kazib:-1,branco:0,brun:0,maurel:0,verdier:0,massard:0,labib:0,lalanne:0,mathieu:0,durif:0,royal:0,jadot:-2,rousseau:-2,autain:0} },
  { id:'q8', theme:'europe', text:'La France devrait sortir de l\'Union européenne et/ou de l\'euro (Frexit).', positions:{philippe:-2,lepen:1,attal:-2,melenchon:1,retailleau:-2,bertrand:-1,glucksmann:-2,guedj:-2,dupontaignan:2,lisnard:-1,batho:0,philippot:2,asselineau:2,arthaud:0,roussel:-1,tondelier:-2,cazeneuve:-2,faure:-2,ruffin:-1,wauquiez:0,devillepin:-2,zemmour:0,bouamrane:-2,egger:0,mikolajczak:-1,kazib:0,branco:0,brun:0,maurel:0,verdier:0,massard:0,labib:0,lalanne:0,mathieu:0,durif:0,royal:-2,jadot:-1,rousseau:-1,autain:0} },
  { id:'q9', theme:'europe', text:'L\'intégration européenne doit être approfondie pour répondre aux crises (climat, sécurité, économie).', positions:{philippe:2,lepen:-2,attal:2,melenchon:-1,retailleau:-1,bertrand:0,glucksmann:2,guedj:2,dupontaignan:-2,lisnard:1,batho:1,philippot:-2,asselineau:-2,arthaud:-1,roussel:-1,tondelier:2,cazeneuve:1,faure:1,ruffin:-1,wauquiez:-2,devillepin:1,zemmour:-2,bouamrane:1,egger:0,mikolajczak:0,kazib:-2,branco:-1,brun:0,maurel:0,verdier:0,massard:0,labib:0,lalanne:0,mathieu:0,durif:0,royal:1,jadot:1,rousseau:1,autain:0} },
  { id:'q10', theme:'institutions', text:'Le référendum d\'initiative citoyenne (RIC) doit être inscrit dans la Constitution.', positions:{philippe:0,lepen:1,attal:-1,melenchon:2,retailleau:0,bertrand:0,glucksmann:-1,guedj:1,dupontaignan:2,lisnard:0,batho:1,philippot:2,asselineau:2,arthaud:0,roussel:2,tondelier:1,cazeneuve:-2,faure:0,ruffin:1,wauquiez:0,devillepin:-1,zemmour:-2,bouamrane:0,egger:2,mikolajczak:1,kazib:0,branco:2,brun:0,maurel:0,verdier:0,massard:0,labib:0,lalanne:0,mathieu:0,durif:0,royal:1,jadot:2,rousseau:2,autain:0} },
  { id:'q11', theme:'institutions', text:'Le régime présidentiel actuel (Ve République) doit être profondément remanié ou remplacé.', positions:{philippe:0,lepen:0,attal:-2,melenchon:2,retailleau:-1,bertrand:0,glucksmann:0,guedj:1,dupontaignan:1,lisnard:0,batho:1,philippot:1,asselineau:1,arthaud:1,roussel:2,tondelier:2,cazeneuve:-1,faure:1,ruffin:2,wauquiez:0,devillepin:1,zemmour:-1,bouamrane:0,egger:2,mikolajczak:1,kazib:2,branco:2,brun:0,maurel:0,verdier:0,massard:0,labib:0,lalanne:0,mathieu:0,durif:0,royal:1,jadot:2,rousseau:2,autain:0} },
  { id:'q12', theme:'economie', text:'Les très grandes fortunes et les revenus du capital doivent être davantage taxés pour financer les services publics.', positions:{philippe:-1,lepen:0,attal:0,melenchon:2,retailleau:-1,bertrand:-1,glucksmann:2,guedj:2,dupontaignan:0,lisnard:0,batho:2,philippot:0,asselineau:1,arthaud:2,roussel:2,tondelier:2,cazeneuve:0,faure:2,ruffin:2,wauquiez:-2,devillepin:0,zemmour:-2,bouamrane:1,egger:0,mikolajczak:0,kazib:2,branco:1,brun:0,maurel:0,verdier:0,massard:0,labib:0,lalanne:0,mathieu:0,durif:0,royal:1,jadot:2,rousseau:2,autain:0} },
  { id:'q13', theme:'immigration', text:'Le droit du sol doit être restreint ou supprimé.', positions:{philippe:1,lepen:2,attal:0,melenchon:-2,retailleau:2,bertrand:1,glucksmann:-2,guedj:-2,dupontaignan:2,lisnard:1,batho:-2,philippot:1,asselineau:0,arthaud:-2,roussel:-2,tondelier:-2,cazeneuve:-1,faure:-2,ruffin:-1,wauquiez:2,devillepin:-1,zemmour:2,bouamrane:-1,egger:0,mikolajczak:0,kazib:-2,branco:-1,brun:0,maurel:0,verdier:0,massard:0,labib:0,lalanne:0,mathieu:0,durif:0,royal:-1,jadot:-2,rousseau:-2,autain:-2} },
  { id:'q14', theme:'securite', text:'Il faut instaurer des peines planchers et construire massivement des places de prison.', positions:{philippe:1,lepen:2,attal:1,melenchon:-2,retailleau:2,bertrand:2,glucksmann:-1,guedj:-1,dupontaignan:2,lisnard:2,batho:-1,philippot:1,asselineau:1,arthaud:-2,roussel:0,tondelier:-2,cazeneuve:0,faure:-1,ruffin:-1,wauquiez:2,devillepin:1,zemmour:2,bouamrane:1,egger:0,mikolajczak:0,kazib:-2,branco:-1,brun:0,maurel:0,verdier:0,massard:0,labib:0,lalanne:0,mathieu:0,durif:0,royal:1,jadot:-1,rousseau:-2,autain:-2} },
  { id:'q15', theme:'ecologie', text:'L\'agriculture doit être réorientée vers l\'agroécologie et la réduction des pesticides, quitte à faire baisser certains rendements.', positions:{philippe:-1,lepen:-2,attal:-1,melenchon:2,retailleau:-2,bertrand:-1,glucksmann:1,guedj:1,dupontaignan:-1,lisnard:-2,batho:2,philippot:-1,asselineau:0,arthaud:0,roussel:1,tondelier:2,cazeneuve:0,faure:1,ruffin:2,wauquiez:-2,devillepin:0,zemmour:-2,bouamrane:0,egger:0,mikolajczak:1,kazib:1,branco:1,brun:0,maurel:0,verdier:0,massard:0,labib:0,lalanne:0,mathieu:0,durif:0,royal:1,jadot:2,rousseau:2,autain:2} },
  { id:'q16', theme:'economie', text:'Des secteurs stratégiques (énergie, rail, autoroutes) doivent être renationalisés.', positions:{philippe:-2,lepen:1,attal:-2,melenchon:2,retailleau:-1,bertrand:-1,glucksmann:0,guedj:1,dupontaignan:2,lisnard:-2,batho:1,philippot:2,asselineau:2,arthaud:2,roussel:2,tondelier:1,cazeneuve:0,faure:1,ruffin:2,wauquiez:-1,devillepin:0,zemmour:0,bouamrane:1,egger:0,mikolajczak:0,kazib:2,branco:1,brun:0,maurel:0,verdier:0,massard:0,labib:0,lalanne:0,mathieu:0,durif:0,royal:1,jadot:1,rousseau:1,autain:2} },
  { id:'q17', theme:'social', text:'Le versement des prestations sociales doit être conditionné à une activité ou à une contrepartie.', positions:{philippe:1,lepen:1,attal:2,melenchon:-2,retailleau:2,bertrand:1,glucksmann:-1,guedj:-1,dupontaignan:1,lisnard:2,batho:-1,philippot:0,asselineau:0,arthaud:-2,roussel:-2,tondelier:-2,cazeneuve:1,faure:-1,ruffin:-2,wauquiez:2,devillepin:0,zemmour:2,bouamrane:0,egger:0,mikolajczak:0,kazib:-2,branco:-1,brun:0,maurel:0,verdier:0,massard:0,labib:0,lalanne:0,mathieu:0,durif:0,royal:0,jadot:-1,rousseau:-2,autain:-2} },
  { id:'q18', theme:'institutions', text:'Il faut introduire une part de proportionnelle aux élections législatives.', positions:{philippe:0,lepen:2,attal:0,melenchon:1,retailleau:-1,bertrand:-1,glucksmann:1,guedj:1,dupontaignan:2,lisnard:0,batho:2,philippot:2,asselineau:2,arthaud:1,roussel:2,tondelier:2,cazeneuve:0,faure:2,ruffin:2,wauquiez:-1,devillepin:1,zemmour:1,bouamrane:1,egger:1,mikolajczak:1,kazib:1,branco:2,brun:0,maurel:0,verdier:0,massard:0,labib:0,lalanne:0,mathieu:0,durif:0,royal:1,jadot:2,rousseau:2,autain:2} },
  { id:'q19', theme:'europe', text:'La France doit maintenir ou renforcer son soutien militaire et financier à l\'Ukraine.', positions:{philippe:2,lepen:-1,attal:2,melenchon:-1,retailleau:1,bertrand:1,glucksmann:2,guedj:2,dupontaignan:-2,lisnard:1,batho:1,philippot:-2,asselineau:-2,arthaud:-1,roussel:-1,tondelier:2,cazeneuve:2,faure:2,ruffin:0,wauquiez:1,devillepin:-1,zemmour:-1,bouamrane:1,egger:0,mikolajczak:0,kazib:-2,branco:0,brun:0,maurel:0,verdier:0,massard:0,labib:0,lalanne:0,mathieu:0,durif:0,royal:0,jadot:2,rousseau:1,autain:0} },
  { id:'q20', theme:'economie', text:'Il faut protéger la production française par des barrières douanières et une préférence nationale ou européenne dans les marchés publics.', positions:{philippe:0,lepen:2,attal:0,melenchon:2,retailleau:1,bertrand:1,glucksmann:1,guedj:1,dupontaignan:2,lisnard:0,batho:1,philippot:2,asselineau:2,arthaud:0,roussel:2,tondelier:1,cazeneuve:0,faure:1,ruffin:2,wauquiez:1,devillepin:1,zemmour:2,bouamrane:1,egger:0,mikolajczak:2,kazib:-1,branco:0,brun:0,maurel:0,verdier:0,massard:0,labib:0,lalanne:0,mathieu:0,durif:0,royal:1,jadot:0,rousseau:1,autain:1} },
  { id:'q21', theme:'institutions', text:'Le président doit se limiter à un rôle d\'arbitre et laisser les grands choix aux citoyens par référendum.', positions:{philippe:-1,lepen:0,attal:-2,melenchon:1,retailleau:-1,bertrand:-1,glucksmann:-1,guedj:0,dupontaignan:1,lisnard:-1,batho:1,philippot:1,asselineau:1,arthaud:0,roussel:1,tondelier:1,cazeneuve:-2,faure:0,ruffin:1,wauquiez:-1,devillepin:-1,zemmour:-2,bouamrane:0,egger:2,mikolajczak:1,kazib:0,branco:2,brun:0,maurel:0,verdier:0,massard:0,labib:0,lalanne:0,mathieu:0,durif:0,royal:-1,jadot:1,rousseau:1,autain:1} },
];
